List<String> healthQuotes = [
  "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship. - Buddha",
  "The greatest wealth is health. - Virgil",
  "Health is not just about what you're eating. It's also about what you're thinking and saying. - Unknown",
  "A healthy outside starts from the inside. - Robert Urich",
  "Health is a state of complete physical, mental and social well-being, and not merely the absence of disease or infirmity. - World Health Organization",
  "The groundwork of all happiness is health. - Leigh Hunt",
  "Your body hears everything your mind says. Stay positive. Be healthy. - Unknown",
  "Take care of your body. It's the only place you have to live. - Jim Rohn",
  "Healthy citizens are the greatest asset any country can have. - Winston Churchill",
  "A healthy attitude is contagious but don't wait to catch it from others. Be a carrier. - Tom Stoppard",
  "To keep the body in good health is a duty... otherwise, we shall not be able to keep our mind strong and clear. - Buddha",
  "The only way to keep your health is to eat what you don't want, drink what you don't like, and do what you'd rather not. - Mark Twain",
  "Health is the first muse, comprising the magical benefits of air, landscape, and bodily exercise on the mind. - Ralph Waldo Emerson",
  "Health and cheerfulness naturally beget each other. - Joseph Addison",
  "An apple a day keeps the doctor away. - Proverb",
  "The doctor of the future will no longer treat the human frame with drugs, but rather will cure and prevent disease with nutrition. - Thomas Edison",
  "The doctor is often more to be feared than the disease. - French Proverb",
  "Your body is a temple, but only if you treat it as one. - Astrid Alauda",
  "Happiness is nothing more than good health and a bad memory. - Albert Schweitzer",
  "A good laugh and a long sleep are the best cures in the doctor's book. - Irish Proverb",
  "He who has health has hope, and he who has hope has everything. - Arabian Proverb",
  "True healthcare reform starts in your kitchen, not in Washington. - Unknown",
  "The part can never be well unless the whole is well. - Plato",
  "To get rich never risk your health. For it is the truth that health is the wealth of wealth. - Richard Baker",
  "The greatest wealth is health. - Ralph Waldo Emerson",
  "When the heart is at ease, the body is healthy. - Chinese Proverb",
  "Health is not valued till sickness comes. - Thomas Fuller",
  "Health is like money, we never have a true idea of its value until we lose it. - Josh Billings",
  "Happiness lies first of all in health. - George William Curtis",
  "Health is the soul that animates all the enjoyments of life, which fade and are tasteless without it. - Lucius Annaeus Seneca",
  "The foundation of success in life is good health: that is the substratum fortune; it is also the basis of happiness. A person cannot accumulate a fortune very well when he is sick. - P. T. Barnum",
  "Eat right, exercise regularly, die anyway. - Unknown",
  "He who takes medicine and neglects to diet wastes the skill of his doctors. - Chinese Proverb",
  "Let food be thy medicine and medicine be thy food. - Hippocrates",
  "Sickness comes on horseback but departs on foot. - Dutch Proverb",
  "Good health is not something we can buy. However, it can be an extremely valuable savings account. - Anne Wilson Schaef",
  "The greatest of follies is to sacrifice health for any other kind of happiness. - Arthur Schopenhauer",
  "You can't enjoy wealth if you're not in good health. - Unknown",
  "Health is a state of complete harmony of the body, mind, and spirit. When one is free from physical disabilities and mental distractions, the gates of the soul open. - B.K.S. Iyengar",
  "A healthy outside starts from the inside. - Robert Urich",
  "Health is not simply the absence of sickness. - Hannah Green",
  "The body is your temple. Keep it pure and clean for the soul to reside in. - B.K.S. Iyengar",
  "The human body has been designed to resist an infinite number of changes and attacks brought about by its environment. The secret of good health lies in successful adjustment to changing stresses on the body. - Harry J. Johnson",
  "Your body is a temple, but only if you treat it as one. - Astrid Alauda",
  "The groundwork of all happiness is health. - Leigh Hunt",
  "Health is a relationship between you and your body. - Terri Guillemets",
  "Health is not about the weight you lose, but about the life you gain. - Unknown",
  "The first wealth is health. - Ralph Waldo Emerson",
  "To keep the body in good health is a duty... otherwise, we shall not be able to keep our mind strong and clear. - Buddha",
  "A healthy attitude is contagious but don't wait to catch it from others. Be a carrier. - Tom Stoppard",
  "Health is not just about what you're eating. It's also about what you're thinking and saying. - Unknown",
  "The only way to keep your health is to eat what you don't want, drink what you don't like, and do what you'd rather not. - Mark Twain",
  "The doctor of the future will no longer treat the human frame with drugs, but rather will cure and prevent disease with nutrition. - Thomas Edison",
  "Health is like money, we never have a true idea of its value until we lose it. - Josh Billings",
  "A good laugh and a long sleep are the best cures in the doctor's book. - Irish Proverb",
  "Happiness lies first of all in health. - George William Curtis",
  "To get rich never risk your health. For it is the truth that health is the wealth of wealth. - Richard Baker",
  "True healthcare reform starts in your kitchen, not in Washington. - Unknown",
  "The part can never be well unless the whole is well. - Plato",
  "An apple a day keeps the doctor away. - Proverb",
  "The doctor is often more to be feared than the disease. - French Proverb",
  "Your body hears everything your mind says. Stay positive. Be healthy. - Unknown",
  "Sickness comes on horseback but departs on foot. - Dutch Proverb",
  "He who takes medicine and neglects to diet wastes the skill of his doctors. - Chinese Proverb",
  "Let food be thy medicine and medicine be thy food. - Hippocrates",
  "When wealth is lost, nothing is lost; when health is lost, something is lost; when character is lost, all is lost. - Billy Graham",
  "Good health is not something we can buy. However, it can be an extremely valuable savings account. - Anne Wilson Schaef",
  "The greatest of follies is to sacrifice health for any other kind of happiness. - Arthur Schopenhauer",
  "You can't enjoy wealth if you're not in good health. - Unknown",
  "Health is a state of complete harmony of the body, mind, and spirit. When one is free from physical disabilities and mental distractions, the gates of the soul open. - B.K.S. Iyengar",
  "Health is not simply the absence of sickness. - Hannah Green",
  "The body is your temple. Keep it pure and clean for the soul to reside in. - B.K.S. Iyengar",
  "The human body has been designed to resist an infinite number of changes and attacks brought about by its environment. The secret of good health lies in successful adjustment to changing stresses on the body. - Harry J. Johnson",
  "Your body is a temple, but only if you treat it as one. - Astrid Alauda",
  "The groundwork of all happiness is health. - Leigh Hunt",
  "Health is a relationship between you and your body. - Terri Guillemets",
  "Health is not about the weight you lose, but about the life you gain. - Unknown",
  "The first wealth is health. - Ralph Waldo Emerson",
  "To keep the body in good health is a duty... otherwise, we shall not be able to keep our mind strong and clear. - Buddha",
  "A healthy attitude is contagious but don't wait to catch it from others. Be a carrier. - Tom Stoppard",
  "Health is not just about what you're eating. It's also about what you're thinking and saying. - Unknown",
  "The only way to keep your health is to eat what you don't want, drink what you don't like, and do what you'd rather not. - Mark Twain",
  "The doctor of the future will no longer treat the human frame with drugs, but rather will cure and prevent disease with nutrition. - Thomas Edison",
  "Health is like money, we never have a true idea of its value until we lose it. - Josh Billings",
  "A good laugh and a long sleep are the best cures in the doctor's book. - Irish Proverb",
  "Happiness lies first of all in health. - George William Curtis",
  "To get rich never risk your health. For it is the truth that health is the wealth of wealth. - Richard Baker",
  "True healthcare reform starts in your kitchen, not in Washington. - Unknown",
  "The part can never be well unless the whole is well. - Plato",
  "An apple a day keeps the doctor away. - Proverb",
  "The doctor is often more to be feared than the disease. - French Proverb",
  "Your body hears everything your mind says. Stay positive. Be healthy. - Unknown",
  "Sickness comes on horseback but departs on foot. - Dutch Proverb",
  "He who takes medicine and neglects to diet wastes the skill of his doctors. - Chinese Proverb",
  "Let food be thy medicine and medicine be thy food. - Hippocrates",
  "When wealth is lost, nothing is lost; when health is lost, something is lost; when character is lost, all is lost. - Billy Graham",
  "Good health is not something we can buy. However, it can be an extremely valuable savings account. - Anne Wilson Schaef",
  "The greatest of follies is to sacrifice health for any other kind of happiness. - Arthur Schopenhauer",
  "You can't enjoy wealth if you're not in good health. - Unknown",
  "Health is a state of complete harmony of the body, mind, and spirit. When one is free from physical disabilities and mental distractions, the gates of the soul open. - B.K.S. Iyengar",
  "Health is not simply the absence of sickness. - Hannah Green",
  "The body is your temple. Keep it pure and clean for the soul to reside in. - B.K.S. Iyengar",
  "The human body has been designed to resist an infinite number of changes and attacks brought about by its environment. The secret of good health lies in successful adjustment to changing stresses on the body. - Harry J. Johnson",
  "Your body is a temple, but only if you treat it as one. - Astrid Alauda",
  "The groundwork of all happiness is health. - Leigh Hunt",
  "Health is a relationship between you and your body. - Terri Guillemets",
  "Health is not about the weight you lose, but about the life you gain. - Unknown",
  "The first wealth is health. - Ralph Waldo Emerson",
  "To keep the body in good health is a duty... otherwise, we shall not be able to keep our mind strong and clear. - Buddha",
  "A healthy attitude is contagious but don't wait to catch it from others. Be a carrier. - Tom Stoppard",
  "Health is not just about what you're eating. It's also about what you're thinking and saying. - Unknown",
  "The only way to keep your health is to eat what you don't want, drink what you don't like, and do what you'd rather not. - Mark Twain",
  "The doctor of the future will no longer treat the human frame with drugs, but rather will cure and prevent disease with nutrition. - Thomas Edison",
  "Health is like money, we never have a true idea of its value until we lose it. - Josh Billings",
  "A good laugh and a long sleep are the best cures in the doctor's book. - Irish Proverb",
  "Happiness lies first of all in health. - George William Curtis",
  "To get rich never risk your health. For it is the truth that health is the wealth of wealth. - Richard Baker",
  "True healthcare reform starts in your kitchen, not in Washington. - Unknown",
  "The part can never be well unless the whole is well. - Plato",
  "An apple a day keeps the doctor away. - Proverb",
  "The doctor is often more to be feared than the disease. - French Proverb",
  "Your body hears everything your mind says. Stay positive. Be healthy. - Unknown",
  "Sickness comes on horseback but departs on foot. - Dutch Proverb",
  "He who takes medicine and neglects to diet wastes the skill of his doctors. - Chinese Proverb",
  "Let food be thy medicine and medicine be thy food. - Hippocrates",
  "When wealth is lost, nothing is lost; when health is lost, something is lost; when character is lost, all is lost. - Billy Graham",
  "Good health is not something we can buy. However, it can be an extremely valuable savings account. - Anne Wilson Schaef",
  "The greatest of follies is to sacrifice health for any other kind of happiness. - Arthur Schopenhauer",
  "You can't enjoy wealth if you're not in good health. - Unknown",
  "Health is a state of complete harmony of the body, mind, and spirit. When one is free from physical disabilities and mental distractions, the gates of the soul open. - B.K.S. Iyengar",
  "Health is not simply the absence of sickness. - Hannah Green",
  "The body is your temple. Keep it pure and clean for the soul to reside in. - B.K.S. Iyengar",
  "The human body has been designed to resist an infinite number of changes and attacks brought about by its environment. The secret of good health lies in successful adjustment to changing stresses on the body. - Harry J. Johnson",
  "Your body is a temple, but only if you treat it as one. - Astrid Alauda",
  "The groundwork of all happiness is health. - Leigh Hunt",
  "Health is a relationship between you and your body. - Terri Guillemets",
  "Health is not about the weight you lose, but about the life you gain. - Unknown",
  "The first wealth is health. - Ralph Waldo Emerson",
  "To keep the body in good health is a duty... otherwise, we shall not be able to keep our mind strong and clear. - Buddha",
  "A healthy attitude is contagious but don't wait to catch it from others. Be a carrier. - Tom Stoppard",
  "Health is not just about what you're eating. It's also about what you're thinking and saying. - Unknown",
  "The only way to keep your health is to eat what you don't want, drink what you don't like, and do what you'd rather not. - Mark Twain",
  "The doctor of the future will no longer treat the human frame with drugs, but rather will cure and prevent disease with nutrition. - Thomas Edison",
  "Health is like money, we never have a true idea of its value until we lose it. - Josh Billings",
  "A good laugh and a long sleep are the best cures in the doctor's book. - Irish Proverb",
  "Happiness lies first of all in health. - George William Curtis",
  "To get rich never risk your health. For it is the truth that health is the wealth of wealth. - Richard Baker",
  "True healthcare reform starts in your kitchen, not in Washington. - Unknown",
  "The part can never be well unless the whole is well. - Plato",
  "An apple a day keeps the doctor away. - Proverb",
  "The doctor is often more to be feared than the disease. - French Proverb",
  "Your body hears everything your mind says. Stay positive. Be healthy. - Unknown",
  "Sickness comes on horseback but departs on foot. - Dutch Proverb",
  "He who takes medicine and neglects to diet wastes the skill of his doctors. - Chinese Proverb",
  "Let food be thy medicine and medicine be thy food. - Hippocrates",
  "When wealth is lost, nothing is lost; when health is lost, something is lost; when character is lost, all is lost. - Billy Graham",
  "Good health is not something we can buy. However, it can be an extremely valuable savings account. - Anne Wilson Schaef",
  "The greatest of follies is to sacrifice health for any other kind of happiness. - Arthur Schopenhauer",
  "You can't enjoy wealth if you're not in good health. - Unknown",
  "Health is a state of complete harmony of the body, mind, and spirit. When one is free from physical disabilities and mental distractions, the gates of the soul open. - B.K.S. Iyengar",
  "Health is not simply the absence of sickness. - Hannah Green",
  "The body is your temple. Keep it pure and clean for the soul to reside in. - B.K.S. Iyengar",
  "The human body has been designed to resist an infinite number of changes and attacks brought about by its environment. The secret of good health lies in successful adjustment to changing stresses on the body. - Harry J. Johnson",
  "Your body is a temple, but only if you treat it as one. - Astrid Alauda",
  "The groundwork of all happiness is health. - Leigh Hunt",
  "Health is a relationship between you and your body. - Terri Guillemets",
  "Health is not about the weight you lose, but about the life you gain. - Unknown",
  "The first wealth is health. - Ralph Waldo Emerson",
  "To keep the body in good health is a duty... otherwise, we shall not be able to keep our mind strong and clear. - Buddha",
  "A healthy attitude is contagious but don't wait to catch it from others. Be a carrier. - Tom Stoppard",
  "Health is not just about what you're eating. It's also about what you're thinking and saying. - Unknown",
  "The only way to keep your health is to eat what you don't want, drink what you don't like, and do what you'd rather not. - Mark Twain",
  "The doctor of the future will no longer treat the human frame with drugs, but rather will cure and prevent disease with nutrition. - Thomas Edison",
  "Health is like money, we never have a true idea of its value until we lose it. - Josh Billings",
  "A good laugh and a long sleep are the best cures in the doctor's book. - Irish Proverb",
  "Happiness lies first of all in health. - George William Curtis",
  "To get rich never risk your health. For it is the truth that health is the wealth of wealth. - Richard Baker",
  "True healthcare reform starts in your kitchen, not in Washington. - Unknown",
  "The part can never be well unless the whole is well. - Plato",
  "An apple a day keeps the doctor away. - Proverb",
  "The doctor is often more to be feared than the disease. - French Proverb",
  "Your body hears everything your mind says. Stay positive. Be healthy. - Unknown",
  "Sickness comes on horseback but departs on foot. - Dutch Proverb",
  "He who takes medicine and neglects to diet wastes the skill of his doctors. - Chinese Proverb",
  "Let food be thy medicine and medicine be thy food. - Hippocrates",
  "When wealth is lost, nothing is lost; when health is lost, something is lost; when character is lost, all is lost. - Billy Graham",
  "Good health is not something we can buy. However, it can be an extremely valuable savings account. - Anne Wilson Schaef",
  "The greatest of follies is to sacrifice health for any other kind of happiness. - Arthur Schopenhauer",
  "You can't enjoy wealth if you're not in good health. - Unknown",
  "Health is a state of complete harmony of the body, mind, and spirit. When one is free from physical disabilities and mental distractions, the gates of the soul open. - B.K.S. Iyengar",
  "Health is not simply the absence of sickness. - Hannah Green",
  "The body is your temple. Keep it pure and clean for the soul to reside in. - B.K.S. Iyengar",
  "The human body has been designed to resist an infinite number of changes and attacks brought about by its environment. The secret of good health lies in successful adjustment to changing stresses on the body. - Harry J. Johnson",
  "Your body is a temple, but only if you treat it as one. - Astrid Alauda",
  "The groundwork of all happiness is health. - Leigh Hunt",
  "Health is a relationship between you and your body. - Terri Guillemets",
  "Health is not about the weight you lose, but about the life you gain. - Unknown",
  "The first wealth is health. - Ralph Waldo Emerson",
  "To keep the body in good health is a duty... otherwise, we shall not be able to keep our mind strong and clear. - Buddha",
  "A healthy attitude is contagious but don't wait to catch it from others. Be a carrier. - Tom Stoppard",
  "Health is not just about what you're eating. It's also about what you're thinking and saying. - Unknown",
  "The only way to keep your health is to eat what you don't want, drink what you don't like, and do what you'd rather not. - Mark Twain",
  "The doctor of the future will no longer treat the human frame with drugs, but rather will cure and prevent disease with nutrition. - Thomas Edison",
  "Health is like money, we never have a true idea of its value until we lose it. - Josh Billings",
  "A good laugh and a long sleep are the best cures in the doctor's book. - Irish Proverb",
  "Happiness lies first of all in health. - George William Curtis",
  "To get rich never risk your health. For it is the truth that health is the wealth of wealth. - Richard Baker",
  "True healthcare reform starts in your kitchen, not in Washington. - Unknown",
  "The part can never be well unless the whole is well. - Plato",
  "An apple a day keeps the doctor away. - Proverb",
  "The doctor is often more to be feared than the disease. - French Proverb",
  "Your body hears everything your mind says. Stay positive. Be healthy. - Unknown",
  "Sickness comes on horseback but departs on foot. - Dutch Proverb",
  "He who takes medicine and neglects to diet wastes the skill of his doctors. - Chinese Proverb",
  "Let food be thy medicine and medicine be thy food. - Hippocrates",
  "When wealth is lost, nothing is lost; when health is lost, something is lost; when character is lost, all is lost. - Billy Graham",
  "Good health is not something we can buy. However, it can be an extremely valuable savings account. - Anne Wilson Schaef",
  "The greatest of follies is to sacrifice health for any other kind of happiness. - Arthur Schopenhauer",
  "You can't enjoy wealth if you're not in good health. - Unknown",
  "Health is a state of complete harmony of the body, mind, and spirit. When one is free from physical disabilities and mental distractions, the gates of the soul open. - B.K.S. Iyengar",
  "Health is not simply the absence of sickness. - Hannah Green",
  "The body is your temple. Keep it pure and clean for the soul to reside in. - B.K.S. Iyengar",
  "The human body has been designed to resist an infinite number of changes and attacks brought about by its environment. The secret of good health lies in successful adjustment to changing stresses on the body. - Harry J. Johnson",
  "Your body is a temple, but only if you treat it as one. - Astrid Alauda",
  "The groundwork of all happiness is health. - Leigh Hunt",
  "Health is a relationship between you and your body. - Terri Guillemets",
  "Health is not about the weight you lose, but about the life you gain. - Unknown",
  "The first wealth is health. - Ralph Waldo Emerson",
  "To keep the body in good health is a duty... otherwise, we shall not be able to keep our mind strong and clear. - Buddha",
  "A healthy attitude is contagious but don't wait to catch it from others. Be a carrier. - Tom Stoppard",
  "Health is not just about what you're eating. It's also about what you're thinking and saying. - Unknown",
  "The only way to keep your health is to eat what you don't want, drink what you don't like, and do what you'd rather not. - Mark Twain",
  "The doctor of the future will no longer treat the human frame with drugs, but rather will cure and prevent disease with nutrition. - Thomas Edison",
  "Health is like money, we never have a true idea of its value until we lose it. - Josh Billings",
  "A good laugh and a long sleep are the best cures in the doctor's book. - Irish Proverb",
  "Happiness lies first of all in health. - George William Curtis",
  "To get rich never risk your health. For it is the truth that health is the wealth of wealth. - Richard Baker",
  "True healthcare reform starts in your kitchen, not in Washington. - Unknown",
  "The part can never be well unless the whole is well. - Plato",
  "An apple a day keeps the doctor away. - Proverb",
  "The doctor is often more to be feared than the disease. - French Proverb",
  "Your body hears everything your mind says. Stay positive. Be healthy. - Unknown",
  "Sickness comes on horseback but departs on foot. - Dutch Proverb",
  "He who takes medicine and neglects to diet wastes the skill of his doctors. - Chinese Proverb",
  "Let food be thy medicine and medicine be thy food. - Hippocrates",
  "When wealth is lost, nothing is lost; when health is lost, something is lost; when character is lost, all is lost. - Billy Graham",
  "Good health is not something we can buy. However, it can be an extremely valuable savings account. - Anne Wilson Schaef",
  "The greatest of follies is to sacrifice health for any other kind of happiness. - Arthur Schopenhauer",
  "You can't enjoy wealth if you're not in good health. - Unknown",
  "Health is a state of complete harmony of the body, mind, and spirit. When one is free from physical disabilities and mental distractions, the gates of the soul open. - B.K.S. Iyengar",
  "Health is not simply the absence of sickness. - Hannah Green",
  "The body is your temple. Keep it pure and clean for the soul to reside in. - B.K.S. Iyengar",
  "The human body has been designed to resist an infinite number of changes and attacks brought about by its environment. The secret of good health lies in successful adjustment to changing stresses on the body. - Harry J. Johnson",
  "Your body is a temple, but only if you treat it as one. - Astrid Alauda",
  "The groundwork of all happiness is health. - Leigh Hunt",
  "Health is a relationship between you and your body. - Terri Guillemets",
  "Health is not about the weight you lose, but about the life you gain. - Unknown",
  "The first wealth is health. - Ralph Waldo Emerson",
  "To keep the body in good health is a duty... otherwise, we shall not be able to keep our mind strong and clear. - Buddha",
  "A healthy attitude is contagious but don't wait to catch it from others. Be a carrier. - Tom Stoppard",
  "Health is not just about what you're eating. It's also about what you're thinking and saying. - Unknown",
  "The only way to keep your health is to eat what you don't want, drink what you don't like, and do what you'd rather not. - Mark Twain",
  "The doctor of the future will no longer treat the human frame with drugs, but rather will cure and prevent disease with nutrition. - Thomas Edison",
  "Health is like money, we never have a true idea of its value until we lose it. - Josh Billings",
  "A good laugh and a long sleep are the best cures in the doctor's book. - Irish Proverb",
  "Happiness lies first of all in health. - George William Curtis",
  "To get rich never risk your health. For it is the truth that health is the wealth of wealth. - Richard Baker",
  "True healthcare reform starts in your kitchen, not in Washington. - Unknown",
  "The part can never be well unless the whole is well. - Plato",
  "An apple a day keeps the doctor away. - Proverb",
  "The doctor is often more to be feared than the disease. - French Proverb",
  "Your body hears everything your mind says. Stay positive. Be healthy. - Unknown",
  "Sickness comes on horseback but departs on foot. - Dutch Proverb",
  "He who takes medicine and neglects to diet wastes the skill of his doctors. - Chinese Proverb",
  "Let food be thy medicine and medicine be thy food. - Hippocrates",
  "When wealth is lost, nothing is lost; when health is lost, something is lost; when character is lost, all is lost. - Billy Graham",
  "Good health is not something we can buy. However, it can be an extremely valuable savings account. - Anne Wilson Schaef",
  "The greatest of follies is to sacrifice health for any other kind of happiness. - Arthur Schopenhauer",
  "You can't enjoy wealth if you're not in good health. - Unknown",
  "Health is a state of complete harmony of the body, mind, and spirit. When one is free from physical disabilities and mental distractions, the gates of the soul open. - B.K.S. Iyengar",
  "Health is not simply the absence of sickness. - Hannah Green",
  "The body is your temple. Keep it pure and clean for the soul to reside in. - B.K.S. Iyengar",
  "The human body has been designed to resist an infinite number of changes and attacks brought about by its environment. The secret of good health lies in successful adjustment to changing stresses on the body. - Harry J. Johnson",
  "Your body is a temple, but only if you treat it as one. - Astrid Alauda",
  "The groundwork of all happiness is health. - Leigh Hunt",
  "Health is a relationship between you and your body. - Terri Guillemets",
  "Health is not about the weight you lose, but about the life you gain. - Unknown",
  "The first wealth is health. - Ralph Waldo Emerson",
  "To keep the body in good health is a duty... otherwise, we shall not be able to keep our mind strong and clear. - Buddha",
  "A healthy attitude is contagious but don't wait to catch it from others. Be a carrier. - Tom Stoppard",
  "Health is not just about what you're eating. It's also about what you're thinking and saying. - Unknown",
  "The only way to keep your health is to eat what you don't want, drink what you don't like, and do what you'd rather not. - Mark Twain",
  "The doctor of the future will no longer treat the human frame with drugs, but rather will cure and prevent disease with nutrition. - Thomas Edison",
  "Health is like money, we never have a true idea of its value until we lose it. - Josh Billings",
  "A good laugh and a long sleep are the best cures in the doctor's book. - Irish Proverb",
  "Happiness lies first of all in health. - George William Curtis",
  "To get rich never risk your health. For it is the truth that health is the wealth of wealth. - Richard Baker",
  "True healthcare reform starts in your kitchen, not in Washington. - Unknown",
  "The part can never be well unless the whole is well. - Plato",
  "An apple a day keeps the doctor away. - Proverb",
  "The doctor is often more to be feared than the disease. - French Proverb",
  "Your body hears everything your mind says. Stay positive. Be healthy. - Unknown",
  "Sickness comes on horseback but departs on foot. - Dutch Proverb",
  "He who takes medicine and neglects to diet wastes the skill of his doctors. - Chinese Proverb",
  "Let food be thy medicine and medicine be thy food. - Hippocrates",
  "When wealth is lost, nothing is lost; when health is lost, something is lost; when character is lost, all is lost. - Billy Graham",
  "Good health is not something we can buy. However, it can be an extremely valuable savings account. - Anne Wilson Schaef",
  "The greatest of follies is to sacrifice health for any other kind of happiness. - Arthur Schopenhauer",
  "You can't enjoy wealth if you're not in good health. - Unknown",
  "Health is a state of complete harmony of the body, mind, and spirit. When one is free from physical disabilities and mental distractions, the gates of the soul open. - B.K.S. Iyengar",
  "Health is not simply the absence of sickness. - Hannah Green",
  "The body is your temple. Keep it pure and clean for the soul to reside in. - B.K.S. Iyengar",
  "The human body has been designed to resist an infinite number of changes and attacks brought about by its environment. The secret of good health lies in successful adjustment to changing stresses on the body. - Harry J. Johnson",
  "Your body is a temple, but only if you treat it as one. - Astrid Alauda",
  "The groundwork of all happiness is health. - Leigh Hunt",
  "Health is a relationship between you and your body. - Terri Guillemets",
  "Health is not about the weight you lose, but about the life you gain. - Unknown",
  "The first wealth is health. - Ralph Waldo Emerson",
  "To keep the body in good health is a duty... otherwise, we shall not be able to keep our mind strong and clear. - Buddha",
  "A healthy attitude is contagious but don't wait to catch it from others. Be a carrier. - Tom Stoppard",
  "Health is not just about what you're eating. It's also about what you're thinking and saying. - Unknown",
  "The only way to keep your health is to eat what you don't want, drink what you don't like, and do what you'd rather not. - Mark Twain",
  "The doctor of the future will no longer treat the human frame with drugs, but rather will cure and prevent disease with nutrition. - Thomas Edison",
  "Health is like money, we never have a true idea of its value until we lose it. - Josh Billings",
  "A good laugh and a long sleep are the best cures in the doctor's book. - Irish Proverb",
  "Happiness lies first of all in health. - George William Curtis",
  "To get rich never risk your health. For it is the truth that health is the wealth of wealth. - Richard Baker",
  "True healthcare reform starts in your kitchen, not in Washington. - Unknown",
  "The part can never be well unless the whole is well. - Plato",
  "An apple a day keeps the doctor away. - Proverb",
  "The doctor is often more to be feared than the disease. - French Proverb",
  "Your body hears everything your mind says. Stay positive. Be healthy. - Unknown",
  "Sickness comes on horseback but departs on foot. - Dutch Proverb",
  "He who takes medicine and neglects to diet wastes the skill of his doctors. - Chinese Proverb",
  "Let food be thy medicine and medicine be thy food. - Hippocrates",
  "When wealth is lost, nothing is lost; when health is lost, something is lost; when character is lost, all is lost. - Billy Graham",
  "Good health is not something we can buy. However, it can be an extremely valuable savings account. - Anne Wilson Schaef",
  "The greatest of follies is to sacrifice health for any other kind of happiness. - Arthur Schopenhauer",
  "You can't enjoy wealth if you're not in good health. - Unknown",
  "Health is a state of complete harmony of the body, mind, and spirit. When one is free from physical disabilities and mental distractions, the gates of the soul open. - B.K.S. Iyengar",
  "Health is not simply the absence of sickness. - Hannah Green",
  "The body is your temple. Keep it pure and clean for the soul to reside in. - B.K.S. Iyengar",
  "The human body has been designed to resist an infinite number of changes and attacks brought about by its environment. The secret of good health lies in successful adjustment to changing stresses on the body. - Harry J. Johnson",
  "Your body is a temple, but only if you treat it as one. - Astrid Alauda",
  "The groundwork of all happiness is health. - Leigh Hunt",
  "Health is a relationship between you and your body. - Terri Guillemets",
  "Health is not about the weight you lose, but about the life you gain. - Unknown",
  "The first wealth is health. - Ralph Waldo Emerson",
  "To keep the body in good health is a duty... otherwise, we shall not be able to keep our mind strong and clear. - Buddha",
  "A healthy attitude is contagious but don't wait to catch it from others. Be a carrier. - Tom Stoppard",
  "Health is not just about what you're eating. It's also about what you're thinking and saying. - Unknown",
  "The only way to keep your health is to eat what you don't want, drink what you don't like, and do what you'd rather not. - Mark Twain",
  "The doctor of the future will no longer treat the human frame with drugs, but rather will cure and prevent disease with nutrition. - Thomas Edison",
  "Health is like money, we never have a true idea of its value until we lose it. - Josh Billings",
  "A good laugh and a long sleep are the best cures in the doctor's book. - Irish Proverb",
  "Happiness lies first of all in health. - George William Curtis",
  "To get rich never risk your health. For it is the truth that health is the wealth of wealth. - Richard Baker",
  "True healthcare reform starts in your kitchen, not in Washington. - Unknown",
  "The part can never be well unless the whole is well. - Plato",
  "An apple a day keeps the doctor away. - Proverb",
  "The doctor is often more to be feared than the disease. - French Proverb",
  "Your body hears everything your mind says. Stay positive. Be healthy. - Unknown",
  "Sickness comes on horseback but departs on foot. - Dutch Proverb",
  "He who takes medicine and neglects to diet wastes the skill of his doctors. - Chinese Proverb",
  "Let food be thy medicine and medicine be thy food. - Hippocrates",
  "When wealth is lost, nothing is lost; when health is lost, something is lost; when character is lost, all is lost. - Billy Graham",
  "Good health is not something we can buy. However, it can be an extremely valuable savings account. - Anne Wilson Schaef",
  "The greatest of follies is to sacrifice health for any other kind of happiness. - Arthur Schopenhauer",
  "You can't enjoy wealth if you're not in good health. - Unknown",
  "Health is a state of complete harmony of the body, mind, and spirit. When one is free from physical disabilities and mental distractions, the gates of the soul open. - B.K.S. Iyengar",
  "Health is not simply the absence of sickness. - Hannah Green",
  "The body is your temple. Keep it pure and clean for the soul to reside in. - B.K.S. Iyengar",
  "The human body has been designed to resist an infinite number of changes and attacks brought about by its environment. The secret of good health lies in successful adjustment to changing stresses on the body. - Harry J. Johnson",
  "Your body is a temple, but only if you treat it as one. - Astrid Alauda",
  "The groundwork of all happiness is health. - Leigh Hunt",
  "Health is a relationship between you and your body. - Terri Guillemets",
  "Health is not about the weight you lose, but about the life you gain. - Unknown",
  "The first wealth is health. - Ralph Waldo Emerson",
  "To keep the body in good health is a duty... otherwise, we shall not be able to keep our mind strong and clear. - Buddha",
  "A healthy attitude is contagious but don't wait to catch it from others. Be a carrier. - Tom Stoppard",
  "Health is not just about what you're eating. It's also about what you're thinking and saying. - Unknown",
  "The only way to keep your health is to eat what you don't want, drink what you don't like, and do what you'd rather not. - Mark Twain",
  "The doctor of the future will no longer treat the human frame with drugs, but rather will cure and prevent disease with nutrition. - Thomas Edison",
  "Health is like money, we never have a true idea of its value until we lose it. - Josh Billings",
  "A good laugh and a long sleep are the best cures in the doctor's book. - Irish Proverb",
  "Happiness lies first of all in health. - George William Curtis",
  "To get rich never risk your health. For it is the truth that health is the wealth of wealth. - Richard Baker",
  "True healthcare reform starts in your kitchen, not in Washington. - Unknown",
  "The part can never be well unless the whole is well. - Plato",
  "An apple a day keeps the doctor away. - Proverb",
  "The doctor is often more to be feared than the disease. - French Proverb",
  "Your body hears everything your mind says. Stay positive. Be healthy. - Unknown",
  "Sickness comes on horseback but departs on foot. - Dutch Proverb",
  "He who takes medicine and neglects to diet wastes the skill of his doctors. - Chinese Proverb",
  "Let food be thy medicine and medicine be thy food. - Hippocrates",
  "When wealth is lost, nothing is lost; when health is lost, something is lost; when character is lost, all is lost. - Billy Graham",
  "Good health is not something we can buy. However, it can be an extremely valuable savings account. - Anne Wilson Schaef",
  "The greatest of follies is to sacrifice health for any other kind of happiness. - Arthur Schopenhauer",
  "You can't enjoy wealth if you're not in good health. - Unknown",
  "Health is a state of complete harmony of the body, mind, and spirit. When one is free from physical disabilities and mental distractions, the gates of the soul open. - B.K.S. Iyengar",
  "Health is not simply the absence of sickness. - Hannah Green",
  "The body is your temple. Keep it pure and clean for the soul to reside in. - B.K.S. Iyengar",
  "The human body has been designed to resist an infinite number of changes and attacks brought about by its environment. The secret of good health lies in successful adjustment to changing stresses on the body. - Harry J. Johnson",
  "Your body is a temple, but only if you treat it as one. - Astrid Alauda",
  "The groundwork of all happiness is health. - Leigh Hunt",
  "Health is a relationship between you and your body. - Terri Guillemets",
  "Health is not about the weight you lose, but about the life you gain. - Unknown",
  "The first wealth is health. - Ralph Waldo Emerson",
  "To keep the body in good health is a duty... otherwise, we shall not be able to keep our mind strong and clear. - Buddha",
  "A healthy attitude is contagious but don't wait to catch it from others. Be a carrier. - Tom Stoppard",
  "Health is not just about what you're eating. It's also about what you're thinking and saying. - Unknown",
  "The only way to keep your health is to eat what you don't want, drink what you don't like, and do what you'd rather not. - Mark Twain",
  "The doctor of the future will no longer treat the human frame with drugs, but rather will cure and prevent disease with nutrition. - Thomas Edison",
  "Health is like money, we never have a true idea of its value until we lose it. - Josh Billings",
  "A good laugh and a long sleep are the best cures in the doctor's book. - Irish Proverb",
  "Happiness lies first of all in health. - George William Curtis",
  "To get rich never risk your health. For it is the truth that health is the wealth of wealth. - Richard Baker",
  "True healthcare reform starts in your kitchen, not in Washington. - Unknown",
  "The part can never be well unless the whole is well. - Plato",
  "An apple a day keeps the doctor away. - Proverb",
  "The doctor is often more to be feared than the disease. - French Proverb",
  "Your body hears everything your mind says. Stay positive. Be healthy. - Unknown",
  "Sickness comes on horseback but departs on foot. - Dutch Proverb",
  "He who takes medicine and neglects to diet wastes the skill of his doctors. - Chinese Proverb",
  "Let food be thy medicine and medicine be thy food. - Hippocrates",
  "When wealth is lost, nothing is lost; when health is lost, something is lost; when character is lost, all is lost. - Billy Graham",
  "Good health is not something we can buy. However, it can be an extremely valuable savings account. - Anne Wilson Schaef",
  "The greatest of follies is to sacrifice health for any other kind of happiness. - Arthur Schopenhauer",
  "You can't enjoy wealth if you're not in good health. - Unknown",
  "Health is a state of complete harmony of the body, mind, and spirit. When one is free from physical disabilities and mental distractions, the gates of the soul open. - B.K.S. Iyengar",
  "Health is not simply the absence of sickness. - Hannah Green",
  "The body is your temple. Keep it pure and clean for the soul to reside in. - B.K.S. Iyengar",
  "The human body has been designed to resist an infinite number of changes and attacks brought about by its environment. The secret of good health lies in successful adjustment to changing stresses on the body. - Harry J. Johnson",
  "Your body is a temple, but only if you treat it as one. - Astrid Alauda",
  "The groundwork of all happiness is health. - Leigh Hunt",
  "Health is a relationship between you and your body. - Terri Guillemets",
  "Health is not about the weight you lose, but about the life you gain. - Unknown",
  "The first wealth is health. - Ralph Waldo Emerson",
  "To keep the body in good health is a duty... otherwise, we shall not be able to keep our mind strong and clear. - Buddha",
  "A healthy attitude is contagious but don't wait to catch it from others. Be a carrier. - Tom Stoppard",
  "Health is not just about what you're eating. It's also about what you're thinking and saying. - Unknown",
  "The only way to keep your health is to eat what you don't want, drink what you don't like, and do what you'd rather not. - Mark Twain",
  "The doctor of the future will no longer treat the human frame with drugs, but rather will cure and prevent disease with nutrition. - Thomas Edison",
  "Health is like money, we never have a true idea of its value until we lose it. - Josh Billings",
  "A good laugh and a long sleep are the best cures in the doctor's book. - Irish Proverb",
  "Happiness lies first of all in health. - George William Curtis",
  "To get rich never risk your health. For it is the truth that health is the wealth of wealth. - Richard Baker",
  "True healthcare reform starts in your kitchen, not in Washington. - Unknown",
  "The part can never be well unless the whole is well. - Plato",
  "An apple a day keeps the doctor away. - Proverb",
  "The doctor is often more to be feared than the disease. - French Proverb",
  "Your body hears everything your mind says. Stay positive. Be healthy. - Unknown",
  "Sickness comes on horseback but departs on foot. - Dutch Proverb",
  "He who takes medicine and neglects to diet wastes the skill of his doctors. - Chinese Proverb",
  "Let food be thy medicine and medicine be thy food. - Hippocrates",
  "When wealth is lost, nothing is lost; when health is lost, something is lost; when character is lost, all is lost. - Billy Graham",
  "Good health is not something we can buy. However, it can be an extremely valuable savings account. - Anne Wilson Schaef",
  "The greatest of follies is to sacrifice health for any other kind of happiness. - Arthur Schopenhauer",
  "You can't enjoy wealth if you're not in good health. - Unknown",
  "Health is a state of complete harmony of the body, mind, and spirit. When one is free from physical disabilities and mental distractions, the gates of the soul open. - B.K.S. Iyengar",
  "Health is not simply the absence of sickness. - Hannah Green",
  "The body is your temple. Keep it pure and clean for the soul to reside in. - B.K.S. Iyengar",
  "The human body has been designed to resist an infinite number of changes and attacks brought about by its environment. The secret of good health lies in successful adjustment to changing stresses on the body. - Harry J. Johnson",
  "Your body is a temple, but only if you treat it as one. - Astrid Alauda",
  "The groundwork of all happiness is health. - Leigh Hunt",
  "Health is a relationship between you and your body. - Terri Guillemets",
  "Health is not about the weight you lose, but about the life you gain. - Unknown",
  "The first wealth is health. - Ralph Waldo Emerson",
  "To keep the body in good health is a duty... otherwise, we shall not be able to keep our mind strong and clear. - Buddha",
  "A healthy attitude is contagious but don't wait to catch it from others. Be a carrier. - Tom Stoppard",
  "Health is not just about what you're eating. It's also about what you're thinking and saying. - Unknown",
  "The only way to keep your health is to eat what you don't want, drink what you don't like, and do what you'd rather not. - Mark Twain",
  "The doctor of the future will no longer treat the human frame with drugs, but rather will cure and prevent disease with nutrition. - Thomas Edison",
  "Health is like money, we never have a true idea of its value until we lose it. - Josh Billings",
  "A good laugh and a long sleep are the best cures in the doctor's book. - Irish Proverb",
  "Happiness lies first of all in health. - George William Curtis",
  "To get rich never risk your health. For it is the truth that health is the wealth of wealth. - Richard Baker",
  "True healthcare reform starts in your kitchen, not in Washington. - Unknown",
  "The part can never be well unless the whole is well. - Plato",
  "An apple a day keeps the doctor away. - Proverb",
  "The doctor is often more to be feared than the disease. - French Proverb",
  "Your body hears everything your mind says. Stay positive. Be healthy. - Unknown",
  "Sickness comes on horseback but departs on foot. - Dutch Proverb",
  "He who takes medicine and neglects to diet wastes the skill of his doctors. - Chinese Proverb",
  "Let food be thy medicine and medicine be thy food. - Hippocrates",
  "When wealth is lost, nothing is lost; when health is lost, something is lost; when character is lost, all is lost. - Billy Graham",
  "Good health is not something we can buy. However, it can be an extremely valuable savings account. - Anne Wilson Schaef",
  "The greatest of follies is to sacrifice health for any other kind of happiness. - Arthur Schopenhauer",
  "You can't enjoy wealth if you're not in good health. - Unknown",
  "Health is a state of complete harmony of the body, mind, and spirit. When one is free from physical disabilities and mental distractions, the gates of the soul open. - B.K.S. Iyengar",
  "Health is not simply the absence of sickness. - Hannah Green",
  "The body is your temple. Keep it pure and clean for the soul to reside in. - B.K.S. Iyengar",
  "The human body has been designed to resist an infinite number of changes and attacks brought about by its environment. The secret of good health lies in successful adjustment to changing stresses on the body. - Harry J. Johnson",
  "Your body is a temple, but only if you treat it as one. - Astrid Alauda",
  "The groundwork of all happiness is health. - Leigh Hunt",
  "Health is a relationship between you and your body. - Terri Guillemets",
  "Health is not about the weight you lose, but about the life you gain. - Unknown",
  "The first wealth is health. - Ralph Waldo Emerson",
  "To keep the body in good health is a duty... otherwise, we shall not be able to keep our mind strong and clear. - Buddha",
  "A healthy attitude is contagious but don't wait to catch it from others. Be a carrier. - Tom Stoppard",
  "Health is not just about what you're eating. It's also about what you're thinking and saying. - Unknown",
  "The only way to keep your health is to eat what you don't want, drink what you don't like, and do what you'd rather not. - Mark Twain",
  "The doctor of the future will no longer treat the human frame with drugs, but rather will cure and prevent disease with nutrition. - Thomas Edison",
  "Health is like money, we never have a true idea of its value until we lose it. - Josh Billings",
  "A good laugh and a long sleep are the best cures in the doctor's book. - Irish Proverb",
  "Happiness lies first of all in health. - George William Curtis",
  "To get rich never risk your health. For it is the truth that health is the wealth of wealth. - Richard Baker",
  "True healthcare reform starts in your kitchen, not in Washington. - Unknown",
  "The part can never be well unless the whole is well. - Plato",
  "An apple a day keeps the doctor away. - Proverb",
  "The doctor is often more to be feared than the disease. - French Proverb",
  "Your body hears everything your mind says. Stay positive. Be healthy. - Unknown",
  "Sickness comes on horseback but departs on foot. - Dutch Proverb",
  "He who takes medicine and neglects to diet wastes the skill of his doctors. - Chinese Proverb",
  "Let food be thy medicine and medicine be thy food. - Hippocrates",
  "When wealth is lost, nothing is lost; when health is lost, something is lost; when character is lost, all is lost. - Billy Graham",
  "Good health is not something we can buy. However, it can be an extremely valuable savings account. - Anne Wilson Schaef",
  "The greatest of follies is to sacrifice health for any other kind of happiness. - Arthur Schopenhauer",
  "You can't enjoy wealth if you're not in good health. - Unknown",
  "Health is a state of complete harmony of the body, mind, and spirit. When one is free from physical disabilities and mental distractions, the gates of the soul open. - B.K.S. Iyengar",
  "Health is not simply the absence of sickness. - Hannah Green",
  "The body is your temple. Keep it pure and clean for the soul to reside in. - B.K.S. Iyengar",
  "The human body has been designed to resist an infinite number of changes and attacks brought about by its environment. The secret of good health lies in successful adjustment to changing stresses on the body. - Harry J. Johnson",
  "Your body is a temple, but only if you treat it as one. - Astrid Alauda",
  "The groundwork of all happiness is health. - Leigh Hunt",
  "Health is a relationship between you and your body. - Terri Guillemets",
  "Health is not about the weight you lose, but about the life you gain. - Unknown",
  "The first wealth is health. - Ralph Waldo Emerson",
];
